name: Release image

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch: { }

permissions:
  contents: write
  packages: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Verify that tag matches Cargo.toml version
        run: |
          version="$(cargo read-manifest --manifest-path=Cargo.toml | jq -r .version)"
          tag="$(echo ${{ github.ref }} | sed 's/refs\/tags\///')"
          if [ "$tag" != "$version" ]; then
            echo "Tag $tag does not match Cargo.toml version $version"
            exit 1
          fi
      - name: Create release
        run: |
          version="$(cargo read-manifest --manifest-path=Cargo.toml | jq -r .version)"
          echo "Creating release $version"
          gh release create $version -t $version --generate-notes -d
  upload_source_to_release:
    needs:
      - create_release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Upload source code
        run: |
          version="$(cargo read-manifest --manifest-path=Cargo.toml | jq -r .version)"
          tar czf forsinka-$version-sources.tar.gz Cargo.toml Cargo.lock src Cargo.toml
          gh release upload "$version" forsinka-$version-sources.tar.gz
  build_release:
    needs:
      - create_release
    runs-on: ${{ matrix.target.runs-on }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - toolchain: x86_64-unknown-linux-gnu
            runs-on: ubuntu-latest
            cargo: cargo
            suffix: ""
          # - toolchain: aarch64-unknown-linux-gnu
          #  runs-on: ubuntu-latest
          #  cargo: cross
          #  suffix: ""
          # - toolchain: x86_64-apple-darwin
          #  runs-on: macos-latest
          #  cargo: cargo
          #  suffix: ""
          - toolchain: aarch64-apple-darwin
            runs-on: macos-latest
            cargo: cargo
            suffix: ""

    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust toolchain for ${{ matrix.target.toolchain }}
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target.toolchain }}
      - uses: Swatinem/rust-cache@v2
      - uses: cargo-bins/cargo-binstall@main
        if: ${{ matrix.target.cargo == 'cross' }}
      - name: Install cross
        if: ${{ matrix.target.cargo == 'cross' }}
        run: cargo binstall -y --force cross
      - name: build release
        run: ${{ matrix.target.cargo }} build --release --target "${{ matrix.target.toolchain }}"
      - name: rename release
        shell: bash
        run: |
          version="$(cargo read-manifest --manifest-path=Cargo.toml | jq -r .version)"
          bin_name=forsinka-${{ matrix.target.toolchain }}${{ matrix.target.suffix }}
          mv target/${{ matrix.target.toolchain }}/release/forsinka${{ matrix.target.suffix }} $bin_name
          if [[ "${{ matrix.target.runs-on }}" == "macos-latest" ]]; then
            shasum -a 256 $bin_name > $bin_name.sha256
          else
            sha256sum $bin_name > $bin_name.sha256
          fi
          gh release upload "$version" $bin_name $bin_name.sha256

  publish_release:
    runs-on: ubuntu-latest
    needs:
      - build_release
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Publish release
        run: |
          version="$(cargo read-manifest --manifest-path Cargo.toml | jq -r .version)"
          gh release edit "$version" --draft=false

  build_images:
    name: Build multiplatform image for ghcr.io
    needs:
      - build_release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Fetch release artifacts for linux/arm64 and linux/amd64
        run: |
          version="$(cargo read-manifest --manifest-path Cargo.toml | jq -r .version)"
          gh release download "$version"
          cp forsinka-x86_64-unknown-linux-gnu forsinka-amd64
          # cp forsinka-aarch64-unknown-linux-gnu forsinka-arm64
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: |
          version="$(cargo read-manifest --manifest-path Cargo.toml | jq -r .version)"
          docker buildx create --use
          docker buildx build . \
            --platform "linux/amd64" \
            -t ghcr.io/${{ github.repository }}:latest \
            -t ghcr.io/${{ github.repository }}:$version \
            --push
